//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long CompetitonId { get; set; }
        public long CompetitorId { get; set; }
        public Nullable<bool> Status { get; set; }
        public long Id { get; set; }
    
        public virtual Competiton Competiton { get; set; }
        public virtual Competitor Competitor { get; set; }
    }
}
