//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sponsor_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public long Id { get; set; }
        public string CardNo { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string CVV { get; set; }
    }
}
