//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sponsor_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        public long Id { get; set; }
        public string SponsorName { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
        public long CompetitorId { get; set; }
        public long CurrencyId { get; set; }
    
        public virtual Competitor Competitor { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
